const mockRestaurants = [
  
     {
    id: "1",
    name: "Knightro's",
    location: "Recreation & Wellness Center",
    cuisine: "Dining Hall",
    waitTime: 3,
    crowdLevel: "low",
    hours: "7:00 AM - 8:00 PM",
    daysOpen: "Mon-Fri",
    coordinates: { lat: 28.6042, lng: -81.1974 },
    menu: [
      {
        id: "knight-1",
        name: "Hamburgers",
        price: 6.49,
        category: "Dinner",
      },
      {
        id: "knight-2",
        name: "Steak",
        price: 25.99,
        category: "Dinner",
      },
      {
        id: "knight-3",
        name: "Acai Bowl",
        price: 8.99,
        category: "Breakfast",
      },
      {
        id: "knight-4",
        name: "Yogurt Parfait",
        price: 5.49,
        category: "Breakfast",
      },
      {
        id: "knight-5",
        name: "Turkey Wrap",
        price: 7.99,
        category: "Dinner",
      },
      {
        id: "knight-6",
        name: "Chicken Salad",
        price: 9.49,
        category: "Lunch",
      },
      {
        id: "knight-7",
        name: "Granola Bar",
        price: 2.49,
        category: "Snacks",
      },
    ],
  },
  {
    id: "2",
    name: "63 South",
    location: "Trevor Colbourn Hall",
    cuisine: "Dining Hall",
    waitTime: 9,
    crowdLevel: "medium",
    hours: "7:30 AM - 8:00 PM",
    coordinates: { lat: 28.6015, lng: -81.2018 },
    menu: [
      {
        id: "63s-1",
        name: "Omelet",
        price: 7.99,
        category: "Breakfast",
      },
      {
        id: "63s-2",
        name: "Pancakes",
        price: 5.99,
        category: "Breakfast",
      },
      {
        id: "63s-3",
        name: "French Toast",
        price: 6.49,
        category: "Breakfast",
      },
      {
        id: "63s-4",
        name: "Grilled Chicken",
        price: 9.99,
        category: "Dinner",
      },
      {
        id: "63s-5",
        name: "Pasta",
        price: 8.99,
        category: "Dinner",
      },
      {
        id: "63s-6",
        name: "Salad",
        price: 7.99,
        category: "Lunch",
      },
      {
        id: "63s-7",
        name: "Pizza",
        price: 3.49,
        category: "Dinner",
      },
      {
        id: "63s-8",
        name: "Soup",
        price: 4.99,
        category: "Lunch",
      },
    ],
  },
  {
    id: "3",
    name: "Barnie's Coffee & Tea Company",
    location: "Library",
    cuisine: "Coffee & Tea",
    waitTime: 7,
    crowdLevel: "medium",
    hours: "7:30 AM - 6:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "barn-1",
        name: "House Blend Coffee",
        price: 2.99,
        category: "Hot Coffee",
      },
      {
        id: "barn-2",
        name: "Caffe Latte",
        price: 4.49,
        category: "Hot Coffee",
      },
      {
        id: "barn-3",
        name: "Cappuccino",
        price: 4.29,
        category: "Hot Coffee",
      },
      {
        id: "barn-4",
        name: "Iced Coffee",
        price: 3.79,
        category: "Cold Drinks",
      },
      {
        id: "barn-5",
        name: "Chai Tea Latte",
        price: 4.79,
        category: "Hot Tea",
      },
      {
        id: "barn-6",
        name: "Muffin",
        price: 3.49,
        category: "Pastries",
      },
      {
        id: "barn-7",
        name: "Bagel",
        price: 3.99,
        category: "Pastries",
      },
    ],
  },
  {
    id: "4",
    name: "Bento Sushi",
    location: "Student Union",
    cuisine: "Japanese",
    waitTime: 10,
    crowdLevel: "medium",
    hours: "11:00 AM - 7:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "bento-1",
        name: "California Roll",
        price: 6.99,
        category: "Rolls",
      },
      {
        id: "bento-2",
        name: "Spicy Tuna Roll",
        price: 7.99,
        category: "Rolls",
      },
      {
        id: "bento-3",
        name: "Philadelphia Roll",
        price: 7.49,
        category: "Rolls",
      },
      {
        id: "bento-4",
        name: "Dragon Roll",
        price: 9.99,
        category: "Specialty Rolls",
      },
      {
        id: "bento-5",
        name: "Rainbow Roll",
        price: 10.99,
        category: "Specialty Rolls",
      },
      {
        id: "bento-6",
        name: "Soup",
        price: 3.99,
        category: "Sides",
      },
      {
        id: "bento-7",
        name: "Poke Bowl",
        price: 12.99,
        category: "Entree",
      },
    ],
  },
  {
    id: "5",
    name: "Café Bustelo",
    location: "Tech Commons",
    cuisine: "Latin Coffee",
    waitTime: 5,
    crowdLevel: "low",
    hours: "8:00 AM - 5:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "bust-1",
        name: "Café Cubano",
        price: 2.49,
        category: "Coffee",
      },
      {
        id: "bust-2",
        name: "Cortadito",
        price: 3.49,
        category: "Coffee",
      },
      {
        id: "bust-3",
        name: "Café con Leche",
        price: 3.99,
        category: "Coffee",
      },
      {
        id: "bust-4",
        name: "Iced Latte",
        price: 4.49,
        category: "Cold Drinks",
      },
      {
        id: "bust-5",
        name: "Empanada",
        price: 2.99,
        category: "Pastries",
      },
      {
        id: "bust-6",
        name: "Cuban Sandwich",
        price: 7.99,
        category: "Food",
      },
    ],
  },
  {
    id: "6",
    name: "Chick-fil-A - JTW Center",
    location: "John T. Washington Center",
    cuisine: "Fast Food",
    waitTime: 14,
    crowdLevel: "high",
    hours: "7:00 AM - 8:00 PM",
    daysOpen: "Mon-Fri",
    coordinates: { lat: 28.6017, lng: -81.201 },
    menu: [
      {
        id: "cfa2-1",
        name: "Chick-fil-A Chicken Sandwich",
        price: 4.69,
        category: "Entrees",
      },
      {
        id: "cfa2-2",
        name: "Spicy Chicken Sandwich",
        price: 5.19,
        category: "Entrees",
      },
      {
        id: "cfa2-3",
        name: "Nuggets (8 count)",
        price: 5.49,
        category: "Entrees",
      },
      {
        id: "cfa2-4",
        name: "Nuggets (12 count)",
        price: 7.49,
        category: "Entrees",
      },
      {
        id: "cfa2-5",
        name: "Waffle Fries",
        price: 2.19,
        category: "Sides",
      },
      {
        id: "cfa2-6",
        name: "Mac & Cheese",
        price: 3.25,
        category: "Sides",
      },
      {
        id: "cfa2-7",
        name: "Lemonade",
        price: 2.49,
        category: "Drinks",
      },
    ],
  },
  {
    id: "7",
    name: "Chick-fil-A RWC",
    location: "Recreation & Wellness Center",
    cuisine: "Fast Food",
    waitTime: 8,
    crowdLevel: "medium",
    hours: "10:30 AM - 8:00 PM",
    daysOpen: "Mon-Fri",
    coordinates: { lat: 28.6042, lng: -81.1974 },
    menu: [
      {
        id: "cfa3-1",
        name: "Chick-fil-A Chicken Sandwich",
        price: 4.69,
        category: "Entrees",
      },
      {
        id: "cfa3-2",
        name: "Grilled Chicken Sandwich",
        price: 5.49,
        category: "Entrees",
      },
      {
        id: "cfa3-3",
        name: "Nuggets (8 count)",
        price: 5.49,
        category: "Entrees",
      },
      {
        id: "cfa3-4",
        name: "Waffle Fries",
        price: 2.19,
        category: "Sides",
      },
      {
        id: "cfa3-5",
        name: "Fruit Cup",
        price: 3.49,
        category: "Sides",
      },
      {
        id: "cfa3-6",
        name: "Lemonade",
        price: 2.49,
        category: "Drinks",
      },
    ],
  },
  {
    id: "8",
    name: "Einstein Bros. Bagels",
    location: "Engineering 2",
    cuisine: "Breakfast & Bagels",
    waitTime: 4,
    crowdLevel: "low",
    hours: "7:00 AM - 2:00 PM",
    daysOpen: "Mon-Fri",
    coordinates: { lat: 28.6019, lng: -81.1994 },
    menu: [
      {
        id: "ein-1",
        name: "Plain Bagel",
        price: 3.49,
        category: "Bagels",
      },
      {
        id: "ein-2",
        name: "Everything Bagel with Cream Cheese",
        price: 4.49,
        category: "Bagels",
      },
      {
        id: "ein-3",
        name: "Egg & Cheese Sandwich",
        price: 5.99,
        category: "Breakfast Sandwiches",
      },
      {
        id: "ein-4",
        name: "Bacon, Egg & Cheese",
        price: 6.99,
        category: "Breakfast Sandwiches",
      },
      {
        id: "ein-5",
        name: "Turkey Sausage Sandwich",
        price: 6.99,
        category: "Breakfast Sandwiches",
      },
      {
        id: "ein-6",
        name: "Coffee (Regular)",
        price: 2.49,
        category: "Drinks",
      },
      {
        id: "ein-7",
        name: "Latte",
        price: 4.49,
        category: "Drinks",
      },
    ],
  },
  {
    id: "9",
    name: "Huey Magoo's",
    location: "Student Union",
    cuisine: "Chicken Tenders",
    waitTime: 11,
    crowdLevel: "medium",
    hours: "10:30 AM - 9:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "huey-1",
        name: "Chicken Tenders (3 pcs)",
        price: 7.99,
        category: "Tenders",
      },
      {
        id: "huey-2",
        name: "Chicken Tenders (5 pcs)",
        price: 11.99,
        category: "Tenders",
      },
      {
        id: "huey-3",
        name: "Chicken Sandwich",
        price: 8.49,
        category: "Sandwiches",
      },
      {
        id: "huey-4",
        name: "Grilled Chicken Sandwich",
        price: 8.99,
        category: "Sandwiches",
      },
      {
        id: "huey-5",
        name: "Chicken Salad",
        price: 9.49,
        category: "Salads",
      },
      {
        id: "huey-6",
        name: "French Fries",
        price: 2.99,
        category: "Sides",
      },
      {
        id: "huey-7",
        name: "Toast",
        price: 1.99,
        category: "Sides",
      },
      {
        id: "huey-8",
        name: "Sweet Tea",
        price: 2.49,
        category: "Drinks",
      },
    ],
  },
  {
    id: "10",
    name: "Jimmy John's",
    location: "Addition Arena",
    cuisine: "Sandwiches",
    waitTime: 6,
    crowdLevel: "low",
    hours: "10:00 AM - 9:00 PM",
    coordinates: { lat: 28.608, lng: -81.1995 },
    menu: [
      {
        id: "jj-1",
        name: "Turkey Tom",
        price: 7.49,
        category: "Subs",
      },
      {
        id: "jj-2",
        name: "Big John",
        price: 7.49,
        category: "Subs",
      },
      {
        id: "jj-3",
        name: "Totally Tuna",
        price: 7.99,
        category: "Subs",
      },
      {
        id: "jj-4",
        name: "Italian Night Club",
        price: 8.49,
        category: "Subs",
      },
      {
        id: "jj-5",
        name: "Gargantuan",
        price: 9.99,
        category: "Subs",
      },
      {
        id: "jj-6",
        name: "Chips",
        price: 1.49,
        category: "Sides",
      },
      {
        id: "jj-7",
        name: "Cookie",
        price: 1.99,
        category: "Desserts",
      },
    ],
  },
  {
    id: "11",
    name: "Knightcade",
    location: "Student Union",
    cuisine: "Diner",
    waitTime: 2,
    crowdLevel: "low",
    hours: "12:00 PM - 10:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "kc-1",
        name: "Pizza Slice",
        price: 3.99,
        category: "Food",
      },
      {
        id: "kc-2",
        name: "Hot Dog",
        price: 3.49,
        category: "Food",
      },
      {
        id: "kc-3",
        name: "Nachos",
        price: 4.99,
        category: "Side",
      },
      {
        id: "kc-4",
        name: "Fountain Drink",
        price: 2.49,
        category: "Drinks",
      },
      {
        name: "Burger",
        price: 13.49,
        category: "Entree",
      },
      {
        id: "kc-6",
        name: "Fries",
        price: 2.99,
        category: "sides",
      },
    ],
  },

  {
    id: "13",
    name: "Knightstop - Student Union",
    location: "Student Union",
    cuisine: "Convenience Store",
    waitTime: 2,
    crowdLevel: "low",
    hours: "7:00 AM - 11:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "ks1-1",
        name: "Grab & Go Sandwich",
        price: 5.99,
        category: "Food",
      },
      {
        id: "ks1-2",
        name: "Fresh Salad",
        price: 6.99,
        category: "Food",
      },
      {
        id: "ks1-3",
        name: "Snack Bag",
        price: 2.49,
        category: "Snacks",
      },
      {
        id: "ks1-4",
        name: "Bottled Beverage",
        price: 2.99,
        category: "Drinks",
      },
      {
        id: "ks1-5",
        name: "Energy Drink",
        price: 3.49,
        category: "Drinks",
      },
    ],
  },
  {
    id: "14",
    name: "Knightstop - Athletics Village",
    location: "Athletics Village",
    cuisine: "Convenience Store",
    waitTime: 2,
    crowdLevel: "low",
    hours: "7:00 AM - 10:00 PM",
    coordinates: { lat: 28.605, lng: -81.196 },
    menu: [
      {
        id: "ks2-1",
        name: "Grab & Go Sandwich",
        price: 5.99,
        category: "Food",
      },
      {
        id: "ks2-2",
        name: "Fresh Salad",
        price: 6.99,
        category: "Food",
      },
      {
        id: "ks2-3",
        name: "Snack Bag",
        price: 2.49,
        category: "Snacks",
      },
      {
        id: "ks2-4",
        name: "Bottled Beverage",
        price: 2.99,
        category: "Drinks",
      },
      {
        id: "ks2-5",
        name: "Sports Drink",
        price: 3.29,
        category: "Drinks",
      },
    ],
  },
  {
    id: "15",
    name: "P.O.D. Market",
    location: "Academic Village",
    cuisine: "Market",
    waitTime: 3,
    crowdLevel: "low",
    hours: "7:00 AM - 12:00 AM",
    coordinates: { lat: 28.603, lng: -81.202 },
    menu: [
      {
        id: "pod-1",
        name: "Made-to-Order Sandwich",
        price: 7.49,
        category: "Food",
      },
      {
        id: "pod-2",
        name: "Fresh Salad",
        price: 7.99,
        category: "Food",
      },
      {
        id: "pod-3",
        name: "Hot Breakfast Burrito",
        price: 5.99,
        category: "Breakfast",
      },
      {
        id: "pod-4",
        name: "Fresh Fruit",
        price: 3.49,
        category: "Snacks",
      },
      {
        id: "pod-5",
        name: "Coffee",
        price: 2.49,
        category: "Drinks",
      },
      {
        id: "pod-6",
        name: "Smoothie",
        price: 5.99,
        category: "Drinks",
      },
    ],
  },
  {
    id: "16",
    name: "Panda Express",
    location: "Student Union",
    cuisine: "Chinese",
    waitTime: 10,
    crowdLevel: "medium",
    hours: "10:30 AM - 8:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "panda-1",
        name: "Orange Chicken",
        price: 8.49,
        category: "Entrees",
        description: "Bowl with 1 side & 1 entree",
      },
      {
        id: "panda-2",
        name: "Beijing Beef",
        price: 8.49,
        category: "Entrees",
      },
      {
        id: "panda-3",
        name: "Kung Pao Chicken",
        price: 8.49,
        category: "Entrees",
      },
      {
        id: "panda-4",
        name: "Broccoli Beef",
        price: 9.49,
        category: "Entrees",
      },
      {
        id: "panda-5",
        name: "Plate (2 Entrees)",
        price: 10.99,
        category: "Plates",
        description: "1 side & 2 entrees",
      },
      {
        id: "panda-6",
        name: "Bigger Plate (3 Entrees)",
        price: 12.99,
        category: "Plates",
        description: "1 side & 3 entrees",
      },
      {
        id: "panda-7",
        name: "Fried Rice",
        price: 4.49,
        category: "Sides",
      },
      {
        id: "panda-8",
        name: "Chow Mein",
        price: 4.49,
        category: "Sides",
      },
    ],
  },
  {
    id: "17",
    name: "Qdoba",
    location: "Student Union",
    cuisine: "Mexican",
    waitTime: 8,
    crowdLevel: "low",
    hours: "10:30 AM - 10:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "qdoba-1",
        name: "Chicken Burrito",
        price: 8.99,
        category: "Burritos",
      },
      {
        id: "qdoba-2",
        name: "Steak Burrito",
        price: 9.99,
        category: "Burritos",
      },
      {
        id: "qdoba-3",
        name: "Burrito Bowl",
        price: 8.99,
        category: "Bowls",
      },
      {
        id: "qdoba-4",
        name: "Tacos (3 pcs)",
        price: 8.49,
        category: "Tacos",
      },
      {
        id: "qdoba-5",
        name: "Chicken Quesadilla",
        price: 8.99,
        category: "Quesadillas",
      },
      {
        id: "qdoba-6",
        name: "Nachos",
        price: 7.99,
        category: "Nachos",
      },
      {
        id: "qdoba-7",
        name: "Chips & Queso",
        price: 4.99,
        category: "Sides",
      },
      {
        id: "qdoba-8",
        name: "Chips & Guacamole",
        price: 4.99,
        category: "Sides",
      },
    ],
  },
  {
    id: "18",
    name: "Starbucks - Health and Public Affairs",
    location: "Health and Public Affairs Building",
    cuisine: "Coffee & Cafe",
    waitTime: 12,
    crowdLevel: "high",
    hours: "7:30 AM - 6:00 PM",
    coordinates: { lat: 28.6025, lng: -81.2008 },
    menu: [
      {
        id: "sbux1-1",
        name: "Caffe Latte",
        price: 4.95,
        category: "Hot Drinks",
      },
      {
        id: "sbux1-2",
        name: "Cappuccino",
        price: 4.75,
        category: "Hot Drinks",
      },
      {
        id: "sbux1-3",
        name: "Caramel Macchiato",
        price: 5.45,
        category: "Hot Drinks",
      },
      {
        id: "sbux1-4",
        name: "Iced Coffee",
        price: 3.95,
        category: "Cold Drinks",
      },
      {
        id: "sbux1-5",
        name: "Cold Brew",
        price: 4.45,
        category: "Cold Drinks",
      },
      {
        id: "sbux1-6",
        name: "Frappuccino",
        price: 5.95,
        category: "Cold Drinks",
      },
      {
        id: "sbux1-7",
        name: "Bacon & Egg Sandwich",
        price: 5.45,
        category: "Pastry",
      },
      {
        id: "sbux1-8",
        name: "Butter Croissant",
        price: 3.45,
        category: "Pastry",
      },
    ],
  },
  {
    id: "19",
    name: "Starbucks- Student Union",
    location: "Student Union 2nd Floor",
    cuisine: "Coffee & Cafe",
    waitTime: 16,
    crowdLevel: "high",
    hours: "7:00 AM - 8:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "sbux1-1",
        name: "Caffe Latte",
        price: 4.95,
        category: "Hot Drinks",
      },
      {
        id: "sbux2-2",
        name: "Cappuccino",
        price: 4.75,
        category: "Hot Drinks",
      },
      {
        id: "sbux2-3",
        name: "Caramel Macchiato",
        price: 5.45,
        category: "Hot Drinks",
      },
      {
        id: "sbux2-4",
        name: "Iced Coffee",
        price: 3.95,
        category: "Cold Drinks",
      },
      {
        id: "sbux2-5",
        name: "Cold Brew",
        price: 4.45,
        category: "Cold Drinks",
      },
      {
        id: "sbux2-6",
        name: "Frappuccino",
        price: 5.95,
        category: "Cold Drinks",
      },
      {
        id: "sbux2-7",
        name: "Bacon & Egg Sandwich",
        price: 5.45,
        category: "Pastry",
      },
      {
        id: "sbux2-8",
        name: "Butter Croissant",
        price: 3.45,
        category: "Pastry",
      },
    ],
  },
  {
    id: "20",
    name: "The Halal Shack",
    location: "Student Union",
    cuisine: "Halal Food",
    waitTime: 13,
    crowdLevel: "medium",
    hours: "10:30 AM - 8:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "halal-1",
        name: "Chicken Over Rice",
        price: 9.99,
        category: "Platters",
      },
      {
        id: "halal-2",
        name: "Gyro Over Rice",
        price: 9.99,
        category: "Platters",
      },
      {
        id: "halal-3",
        name: "Combo Platter",
        price: 11.99,
        category: "Platters",
      },
      {
        id: "halal-4",
        name: "Chicken Gyro Wrap",
        price: 8.49,
        category: "Wraps",
      },
      {
        id: "halal-5",
        name: "Falafel Wrap",
        price: 7.99,
        category: "Wraps",
      },
      {
        id: "halal-6",
        name: "Hummus & Pita",
        price: 4.99,
        category: "Sides",
      },
      {
        id: "halal-7",
        name: "Baklava",
        price: 3.49,
        category: "Desserts",
      },
    ],
  },
  {
    id: "21",
    name: "Topper's",
    location: "UCF Fountain",
    cuisine: "Ice Cream",
    waitTime: 4,
    crowdLevel: "low",
    hours: "12:00 PM - 4:00 PM",
    coordinates: { lat: 28.6017, lng: -81.2 },
    menu: [
      {
        id: "top-1",
        name: "Vanilla Ice Cream",
        price: 3.99,
        category: "Ice Cream",
      },
      {
        id: "top-2",
        name: "Chocolate Ice Cream",
        price: 3.99,
        category: "Ice Cream",
      },
      {
        id: "top-3",
        name: "Strawberry Ice Cream",
        price: 3.99,
        category: "Ice Cream",
      },
      {
        id: "top-4",
        name: "Cookie Dough Ice Cream",
        price: 4.49,
        category: "Ice Cream",
      },
      {
        id: "top-5",
        name: "Mint Chocolate Chip",
        price: 4.49,
        category: "Ice Cream",
      },
    ],
  },
  {
    id: "22",
    name: "Which Wich",
    location: "Student Union",
    cuisine: "Sandwiches",
    waitTime: 9,
    crowdLevel: "medium",
    hours: "10:30 AM - 8:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "ww-1",
        name: "Turkey Sandwich",
        price: 7.99,
        category: "Hot Sandwiches",
      },
      {
        id: "ww-2",
        name: "Ham Sandwich",
        price: 7.99,
        category: "Hot Sandwiches",
      },
      {
        id: "ww-3",
        name: "Italian Sandwich",
        price: 8.49,
        category: "Hot Sandwiches",
      },
      {
        id: "ww-4",
        name: "Chicken Sandwich",
        price: 8.99,
        category: "Hot Sandwiches",
      },
      {
        id: "ww-5",
        name: "Meatball Sandwich",
        price: 8.99,
        category: "Hot Sandwiches",
      },
      {
        id: "ww-6",
        name: "Chips",
        price: 1.99,
        category: "Sides",
      },
      {
        id: "ww-7",
        name: "Cookie",
        price: 2.49,
        category: "Desserts",
      },
      {
        id: "ww-8",
        name: "MilkShake",
        price: 4.99,
        category: "Drinks",
      },
    ],
  },
  {
    id: "23",
    name: "Domino's - JTW Center",
    location: "John T. Washington Center",
    cuisine: "Pizza",
    waitTime: 17,
    crowdLevel: "medium",
    hours: "11:00 AM - 2:00 AM",
    coordinates: { lat: 28.6017, lng: -81.201 },
    menu: [
      {
        id: "dom1-1",
        name: "Pepperoni Pizza (Medium)",
        price: 9.99,
        category: "Pizza",
      },
      {
        id: "dom1-2",
        name: "Cheese Pizza (Medium)",
        price: 8.99,
        category: "Pizza",
      },
      {
        id: "dom1-3",
        name: "Pepperoni Pizza (Large)",
        price: 12.99,
        category: "Pizza",
      },
      {
        id: "dom1-4",
        name: "MeatZZa Pizza (Large)",
        price: 14.99,
        category: "Pizza",
      },
      {
        id: "dom1-5",
        name: "Buffalo Wings (8 pcs)",
        price: 7.99,
        category: "Sides",
      },
      {
        id: "dom1-6",
        name: "Breadsticks",
        price: 5.99,
        category: "Sides",
      },
      {
        id: "dom1-7",
        name: "Cookie",
        price: 1.99,
        category: "Desserts",
      },
    ],
  },
  {
    id: "24",
    name: "Domino's - Addition Arena",
    location: "Addition Arena",
    cuisine: "Pizza",
    waitTime: 14,
    crowdLevel: "medium",
    hours: "11:00 AM - 12:00 AM",
    coordinates: { lat: 28.608, lng: -81.1995 },
    menu: [
      {
        id: "dom2-1",
        name: "Pepperoni Pizza (Medium)",
        price: 9.99,
        category: "Pizza",
      },
      {
        id: "dom2-2",
        name: "Cheese Pizza (Medium)",
        price: 8.99,
        category: "Pizza",
      },
      {
        id: "dom2-3",
        name: "Pepperoni Pizza (Large)",
        price: 12.99,
        category: "Pizza",
      },
      {
        id: "dom2-4",
        name: "Buffalo Wings (8 pcs)",
        price: 7.99,
        category: "Sides",
      },
      {
        id: "dom2-5",
        name: "Breadsticks",
        price: 5.99,
        category: "Sides",
      },
    ],
  },
  {
    id: "25",
    name: "Gringos Locos",
    location: "Student Union",
    cuisine: "Mexican",
    waitTime: 11,
    crowdLevel: "medium",
    hours: "11:00 AM - 9:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "gring-1",
        name: "Carne Asada Tacos (3)",
        price: 9.99,
        category: "Tacos",
      },
      {
        id: "gring-2",
        name: "Al Pastor Tacos (3)",
        price: 9.99,
        category: "Tacos",
      },
      {
        id: "gring-3",
        name: "Burrito Bowl",
        price: 10.99,
        category: "Bowls",
      },
      {
        id: "gring-4",
        name: "Quesadilla",
        price: 8.99,
        category: "Quesadillas",
      },
      {
        id: "gring-5",
        name: "Nachos Supreme",
        price: 9.49,
        category: "Nachos",
      },
      {
        id: "gring-6",
        name: "Chips & Salsa",
        price: 3.99,
        category: "Sides",
      },
      {
        id: "gring-7",
        name: "Horchata",
        price: 3.49,
        category: "Drinks",
      },
    ],
  },
  {
    id: "26",
    name: "Knight Shop - Addition Arena",
    location: "Addition Arena",
    cuisine: "Convenience Store",
    waitTime: 2,
    crowdLevel: "low",
    hours: "8:00 AM - 9:00 PM",
    coordinates: { lat: 28.608, lng: -81.1995 },
    menu: [
      {
        id: "ks-1",
        name: "Sandwich",
        price: 6.49,
        category: "Food",
      },
      {
        id: "ks-2",
        name: "Salad",
        price: 7.49,
        category: "Food",
      },
      {
        id: "ks-3",
        name: "Snacks",
        price: 2.49,
        category: "Snacks",
      },
      {
        id: "ks-4",
        name: "Bottled Water",
        price: 2.99,
        category: "Drinks",
      },
      {
        id: "ks-5",
        name: "Energy Drink",
        price: 3.49,
        category: "Drinks",
      },
    ],
  },
  {
    id: "27",
    name: "Dunkin Donuts - Addition Arena",
    location: "Addition Arena",
    cuisine: "Coffee & Donuts",
    waitTime: 8,
    crowdLevel: "medium",
    hours: "6:00 AM - 8:00 PM",
    coordinates: { lat: 28.608, lng: -81.1995 },
    menu: [
      {
        id: "dd-1",
        name: "Coffee",
        price: 2.49,
        category: "Hot Drinks",
      },
      {
        id: "dd-2",
        name: "Latte",
        price: 4.49,
        category: "Hot Drinks",
      },
      {
        id: "dd-3",
        name: "Iced Coffee",
        price: 3.49,
        category: "Cold Drinks",
      },
      {
        id: "dd-4",
        name: "Frozen Coffee",
        price: 4.99,
        category: "Cold Drinks",
      },
      {
        id: "dd-5",
        name: "Glazed Donut",
        price: 1.99,
        category: "Donuts",
      },
      {
        id: "dd-6",
        name: "Dozen Donuts",
        price: 11.99,
        category: "Donuts",
      },
      {
        id: "dd-7",
        name: "Breakfast Sandwich",
        price: 4.99,
        category: "Food",
      },
      {
        id: "dd-8",
        name: "Hash Browns",
        price: 2.49,
        category: "Sides",
      },
    ],
  },
  {
    id: "28",
    name: "Addiotion Areana",
    location: "Addiotion Areana",
    cuisine: "Coffee",
    waitTime: 10,
    crowdLevel: "medium",
    hours: "7:00 AM - 6:00 PM",
    coordinates: { lat: 28.6005, lng: -81.2012 },
    menu: [
      {
        id: "fox1-1",
        name: "Drip Coffee",
        price: 3.49,
        category: "Hot Drinks",
      },
      {
        id: "fox1-2",
        name: "Latte",
        price: 4.99,
        category: "Hot Drinks",
      },
      {
        id: "fox1-3",
        name: "Cappuccino",
        price: 4.79,
        category: "Hot Drinks",
      },
      {
        id: "fox1-4",
        name: "Cold Brew",
        price: 4.49,
        category: "Cold Drinks",
      },
      {
        id: "fox1-5",
        name: "Iced Latte",
        price: 5.29,
        category: "Cold Drinks",
      },
      {
        id: "fox1-6",
        name: "Pastry",
        price: 3.99,
        category: "Food",
      },
    ],
  },

  {
    id: "30",
    name: "Foxtail - Addition Arena",
    location: "Addition Arena",
    cuisine: "Coffee",
    waitTime: 7,
    crowdLevel: "low",
    hours: "7:00 AM - 6:00 PM",
    coordinates: { lat: 28.608, lng: -81.1995 },
    menu: [
      {
        id: "fox3-1",
        name: "Drip Coffee",
        price: 3.49,
        category: "Hot Drinks",
      },
      {
        id: "fox3-2",
        name: "Latte",
        price: 4.99,
        category: "Hot Drinks",
      },
      {
        id: "fox3-3",
        name: "Cappuccino",
        price: 4.79,
        category: "Hot Drinks",
      },
      {
        id: "fox3-4",
        name: "Cold Brew",
        price: 4.49,
        category: "Cold Drinks",
      },
      {
        id: "fox3-5",
        name: "Iced Latte",
        price: 5.29,
        category: "Cold Drinks",
      },
      {
        id: "fox3-6",
        name: "Pastry",
        price: 3.99,
        category: "Food",
      },
    ],
  },
  {
    id: "31",
    name: "Pop Parlor",
    location: "Addition Arena",
    cuisine: "Coffee",
    waitTime: 6,
    crowdLevel: "low",
    hours: "7:30 AM - 5:00 PM",
    coordinates: { lat: 28.608, lng: -81.1995 },
    menu: [
      {
        id: "pop-1",
        name: "Espresso",
        price: 3.29,
        category: "Hot Drinks",
      },
      {
        id: "pop-2",
        name: "Americano",
        price: 3.99,
        category: "Hot Drinks",
      },
      {
        id: "pop-3",
        name: "Latte",
        price: 4.79,
        category: "Hot Drinks",
      },
      {
        id: "pop-4",
        name: "Cold Brew",
        price: 4.29,
        category: "Cold Drinks",
      },
      {
        id: "pop-5",
        name: "Iced Latte",
        price: 5.09,
        category: "Cold Drinks",
      },
      {
        id: "pop-6",
        name: "Ice Pop",
        price: 3.49,
        category: "Dessert",
      },
    ],
  },
  {
    id: "32",
    name: "Burger U",
    location: "Student Union",
    cuisine: "Sport Bar",
    waitTime: 19,
    crowdLevel: "high",
    hours: "10:30 AM - 9:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "burger-1",
        name: "Classic Burger",
        price: 7.99,
        category: "Burgers",
      },
      {
        id: "burger-2",
        name: "Cheeseburger",
        price: 8.49,
        category: "Burgers",
      },
      {
        id: "burger-3",
        name: "Bacon Burger",
        price: 9.49,
        category: "Burgers",
      },
      {
        id: "burger-4",
        name: "Double Burger",
        price: 10.99,
        category: "Burgers",
      },
      {
        id: "burger-5",
        name: "Veggie Burger",
        price: 8.99,
        category: "Burgers",
      },
      {
        id: "burger-6",
        name: "French Fries",
        price: 3.49,
        category: "Sides",
      },
      {
        id: "burger-7",
        name: "Onion Rings",
        price: 4.49,
        category: "Sides",
      },
      {
        id: "burger-8",
        name: "Milkshake",
        price: 4.99,
        category: "Drinks",
      },
    ],
  },
  {
    id: "33",
    name: "Smoothie King - Student Union",
    location: "Student Union",
    cuisine: "Smoothies",
    waitTime: 5,
    crowdLevel: "low",
    hours: "8:00 AM - 8:00 PM",
    coordinates: { lat: 28.6011, lng: -81.2005 },
    menu: [
      {
        id: "sk1-1",
        name: "Strawberry X-Treme",
        price: 7.49,
        category: "Smoothies",
      },
      {
        id: "sk1-2",
        name: "Pineapple Surf",
        price: 7.49,
        category: "Smoothies",
      },
      {
        id: "sk1-3",
        name: "Chocolate Gladiator",
        price: 8.49,
        category: "Protein Smoothies",
      },
      {
        id: "sk1-4",
        name: "Hulk Strawberry",
        price: 8.99,
        category: "Protein Smoothies",
      },
      {
        id: "sk1-5",
        name: "Activator Coffee",
        price: 8.49,
        category: "Coffee Smoothies",
      },
      {
        id: "sk1-6",
        name: "Granola Bar",
        price: 3.99,
        category: "Snacks",
      },
    ],
  },
  {
    id: "34",
    name: "Smoothie King - RWC",
    location: "Recreation & Wellness Center",
    cuisine: "Smoothies",
    waitTime: 4,
    crowdLevel: "low",
    hours: "8:00 AM - 7:00 PM",
    coordinates: { lat: 28.6042, lng: -81.1974 },
    menu: [
      {
        id: "sk2-1",
        name: "Strawberry X-Treme",
        price: 7.49,
        category: "Smoothies",
      },
      {
        id: "sk2-2",
        name: "Pineapple Surf",
        price: 7.49,
        category: "Smoothies",
      },
      {
        id: "sk2-3",
        name: "Chocolate Gladiator",
        price: 8.49,
        category: "Protein Smoothies",
      },
      {
        id: "sk2-4",
        name: "Hulk Strawberry",
        price: 8.99,
        category: "Protein Smoothies",
      },
      {
        id: "sk2-5",
        name: "Activator Coffee",
        price: 8.49,
        category: "Coffee Smoothies",
      },
      {
        id: "sk2-6",
        name: "Granola Bar",
        price: 3.99,
        category: "Snacks",
      },
    ]
  }
];

export default mockRestaurants;